#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
    3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

mem=`free -h | awk '/Mem/{print $3 "/" $2}'`
mem_ratio=`free | awk '/Mem/{print $3 / $2}'`

echo $mem
echo $mem_ratio

# Color
if [ 1 -eq "$(echo "${mem_ratio} < 0.4" | bc)" ]; then
    echo "#55AAEE"
elif [ 1 -eq "$(echo "${mem_ratio} < 0.7" | bc)" ]; then
    echo "#FFCC66"
else
    echo "#FF0000"
fi
