#!/bin/sh

case $BLOCK_BUTTON in
	1) pavucontrol & ;;
	2) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
	4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
	3) notify-send "🔈 Audio sink" "$(~/bin/which_audio_sink.sh)" ;;
esac

# [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = "Mute: yes" ] && printf "🔇\\n" && exit

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')

if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = "Mute: yes" ]; then
    icon="🔇"
elif [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

if [ "$(pactl get-source-mute @DEFAULT_SOURCE@)" = "Mute: yes" ]; then
    micicon=""
else
    micicon=""
fi

printf "%s %s %s\\n" "$icon" "$vol" "$micicon"
