#!/bin/bash
set -x

DISPLAYS=$(xrandr | grep "\<connected" | awk '{print $1}')
NDISPLAYS=$(echo "$DISPLAYS" | wc -w)

if [[ $NDISPLAYS == 1 ]]; then
	SELECTED=$DISPLAYS
else
	SELECTED=$(echo "$DISPLAYS" | dmenu -i -p "Choose primary display:")
fi

if [[ -n $SELECTED ]]; then
	xrandr --output "$SELECTED" --auto --primary
fi

~/bin/dmenu/display
