#!/bin/bash

# set -x

DISPLAYS=`xrandr | awk '$2 ~ /\<connected/ {print $1}'`
PRIMARY=`xrandr | awk '$2 ~ /\<connected/ {print $1}' | awk '/eDP|LVDS|DP|DVI*/ {print;exit}'`
SECONDARY=`xrandr | awk '$2 ~ /\<connected/ {print $1}' | awk -v a="$PRIMARY" '$0 !~ a'`

OPTIONS=$'single\nleft\nright\nabove\nbelow\nsame'
POS=$(echo "$OPTIONS" | dmenu -i -p "$SECONDARY pos:")

echo "DISPLAYS:" $DISPLAYS
echo "PRIMARY:" $PRIMARY
echo "SECONDARY:" $SECONDARY
echo "POS:" $POS

if [ $POS = "right" ]; then
    xrandr --output $SECONDARY --right-of	$PRIMARY --auto --rotate normal
elif [ $POS = "left" ]; then
    xrandr --output $SECONDARY --left-of	$PRIMARY --auto --rotate normal
elif [ $POS = "above" ]; then
    xrandr --output $SECONDARY --above		$PRIMARY --auto --rotate normal
elif [ $POS = "below" ]; then
    xrandr --output $SECONDARY --below		$PRIMARY --auto --rotate normal
elif [ $POS = "same" ]; then
    xrandr --output $SECONDARY --same-as	$PRIMARY --auto --rotate normal
elif [ $POS = "single" ]; then
    xrandr --output $SECONDARY --off		--output $PRIMARY --auto
fi&

# Update display setting
sed -i -e "s/primdisp .*$/primdisp   $PRIMARY/" ~/.config/i3/config
sed -i -e "s/extdisp .*$/extdisp    $SECONDARY/" ~/.config/i3/config

# Reload i3 config
i3-msg reload
