#!/bin/bash

set -x

DISPLAYS=$(xrandr | awk '/\<connected/ {print $1}')
# PRIMARY=`xrandr | awk '$2 ~ /\<connected/ {print $1}' | awk '/eDP|LVDS|DP|DVI*/ {print;exit}'`
PRIMARY=$(xrandr | grep "primary" | awk '{print $1}')
SECONDARY=$(xrandr | awk '/\<connected/ {print $1}' | awk -v a="$PRIMARY" '$0 !~ a {print;exit}')
STALE=$(xrandr | awk '/\<disconnected [0-9]+x[0-9]/ {print $1}')

OPTIONS=$'single\nleft\nright\nabove\nbelow\nsame'
POS=$(echo "$OPTIONS" | dmenu -i -p "primary: $PRIMARY; $SECONDARY pos:")

echo "DISPLAYS: $DISPLAYS"
echo "PRIMARY: $PRIMARY"
echo "SECONDARY: $SECONDARY"
echo "STALE: $STALE"
echo "POS: $POS"

# Remove disconnected display
if [[ -n $STALE ]]; then
	xrandr --output "$STALE" --auto
fi

xrandr --output "$PRIMARY" --auto
if [ "$POS" = "right" ]; then
	xrandr --output "$SECONDARY" --auto --right-of "$PRIMARY" --rotate normal
elif [ "$POS" = "left" ]; then
	xrandr --output "$SECONDARY" --auto --left-of "$PRIMARY" --rotate normal
elif [ "$POS" = "above" ]; then
	xrandr --output "$SECONDARY" --auto --above "$PRIMARY" --rotate normal
elif [ "$POS" = "below" ]; then
	xrandr --output "$SECONDARY" --auto --below "$PRIMARY" --rotate normal
elif [ "$POS" = "same" ]; then
	xrandr --output "$SECONDARY" --auto --same-as "$PRIMARY" --rotate normal
elif [ "$POS" = "single" ]; then
	xrandr --output "$SECONDARY" --off
	xrandr --output "$PRIMARY" --auto
fi &

# Reload i3 config
i3-msg reload
