#!/usr/bin/sh

# set -x

APPS='pavucontrol\nblueman-manager\ngnome-control-center\narandr\nsystem-config-printer\n'

SELECT=$(echo ${APPS} | dmenu -i -p "GUI settings:")

exec $(XDG_CURRENT_DESKTOP=GNOME exec ${SELECT})
