#!/bin/bash
set +x

get_supported_resolution ()
{
    local res=`xrandr |
        awk -v monitor="^$1 connected" \
            '/connected/ {p = 0}
            $0 ~ monitor {p = 1}
            p &&
            $1 ~ /x/ { print $1 }'`

    echo "$res"
}

ress1=$(get_supported_resolution eDP-1-1)
ress2=$(get_supported_resolution DP-0.2)

res=0
for res1 in $ress1
do
    for res2 in $ress2
    do
        if [[ $res1 == $res2 ]]; then
            res=$res1
            break
        fi
    done
    if [[ $res != 0 ]]; then
        break
    fi
done

echo $res
