#!/bin/bash

option=$'lock\nsuspend\npoweroff\nreboot\nlogoff\n'

mode=$(echo "$option" | dmenu -i -p "System command:")

#echo "Selected mode $mode"

case $mode in
    "lock")     xautolock -locknow ;;
    "suspend")  systemctl suspend ;;
    "poweroff") systemctl poweroff;;
    "reboot")   systemctl reboot ;;
    "logoff")   i3-msg exit ;;
esac
