#!/bin/sh

DISPLAYS=`xrandr | awk '/ connected/{print $1}'`
echo $DISPLAYS

#PRIMARY=$(echo "$DISPLAYS" | dmenu -i -p "Primary:")
PRIMARY='LVDS-1'
SECONDARY=`xrandr | awk '/ connected/{print $1}' | grep -v $PRIMARY | awk '//{print $1}'`

# Change i3/config
sed -i -e 's/set $extdisp.*$/set $extdisp    '$SECONDARY'/g' ~/.config/i3/config

echo "PRI" $PRIMARY
echo "SEC" $SECONDARY

OPTIONS='single\nleft\nright\nabove\nbelow\nsame'
POS=$(echo "$OPTIONS" | dmenu -i -p "Pos:")

echo $POS

if [ $POS = "right" ]; then
    xrandr --output $SECONDARY --right-of	$PRIMARY --auto --rotate normal
elif [ $POS = "left" ]; then
    xrandr --output $SECONDARY --left-of	$PRIMARY --auto --rotate normal
elif [ $POS = "above" ]; then
    xrandr --output $SECONDARY --above		$PRIMARY --auto --rotate normal
elif [ $POS = "below" ]; then
    xrandr --output $SECONDARY --below		$PRIMARY --auto --rotate normal
elif [ $POS = "same" ]; then
    xrandr --output $SECONDARY --same-as	$PRIMARY --auto --rotate normal
elif [ $POS = "single" ]; then
    xrandr --output $SECONDARY --off		--output $PRIMARY --auto
fi&

