#!/bin/bash

option=$'suspend\npoweroff\nreboot\nlock\nlogoff\n'

mode=$(echo "$option" | dmenu -i -p "System command:")

#echo "Selected mode $mode"

case $mode in
    "suspend")  systemctl suspend ;;
    "poweroff") systemctl poweroff;;
    "reboot")   systemctl reboot ;;
    "lock")     playerctl pause ; i3lock-fancy --pixelate --text "***" --desktop ;;
    "logoff")   i3-msg exit ;;
esac
