#!/bin/bash
# set -x
TARGET_FILE='/tmp/tmux_launcher'

# NOTE: Make sure to limit the maxdepth! 5 is still reasonable
find ~/Documents/notes/ ~/projects/ -maxdepth 5 -type d -name ".git" 2>/dev/null | \
    sed 's|/.git$||' | \
    sort -u > $TARGET_FILE

if [[ ${1} == "window" ]]; then
    tmux_launcher window
else
    tmux_launcher
fi
