#!/bin/bash
# set -x


PROJECTS=`find ~/Documents/notes/ -maxdepth 1 -mindepth 1 -type d`
PROJECTS+=$'\n'"`find ~/projects/dotfiles -maxdepth 0 -mindepth 0 -type d`"
PROJECTS+=$'\n'"`find ~/projects/espressif/ ~/projects/bitcraze/ ~/projects/tii/ ~/projects/greenwaves/ ~/projects/others/  -maxdepth 1 -mindepth 1 -type d`"
PROJECTS+=$'\n'"`find ~/projects/playgrounds/  -maxdepth 1 -mindepth 1 -type d`"

#~/projects/coursera/real-time_embedded_systems_concepts_and_practices/assignments/

if [[ ${1} == "window" ]]; then
    SELECTED=`echo "$PROJECTS" | fzf --header "new-tmux-window" --layout=reverse`
else
    SELECTED=`echo "$PROJECTS" | fzf --header "tmux-session" --layout=reverse`
fi

if [[ -z $SELECTED ]]; then
    exit 0
fi

NAME=`echo ${SELECTED} | sed "s|^.*\(/.*/.*$\)|\1|g"`
NAME=${NAME#/}

if [[ -z $1 ]]; then
    # https://koenwoortman.com/tmux-sessions-should-be-nested-with-care-unset-tmux-to-force/
    # 1. First you check if a tmux session exists with a given name.
    tmux has-session -t=$NAME 2> /dev/null

    # 2. Create the session if it doesn't exists.
    if [[ $? -ne 0 ]]; then
      TMUX='' tmux new-session -c "$SELECTED" -d -s "$NAME" -n "MAIN"
    fi

    # 3. Attach if outside of tmux, switch if you're in tmux.
    if [[ -z "$TMUX" ]]; then
      tmux attach -t "$NAME"
    else
      tmux switch-client -t "$NAME"
    fi
elif [[ ${1} == "window" ]]; then
    tmux new-window -n "$NAME" -c "$SELECTED"
fi
